// Conteúdo dos jogos — autoral (CLAUDE.md, regra 6).
//   GLOSSARIO: termo + dica curta. Usado na Memória do Tico (termo ↔ dica),
//     no Caça-palavras (acha o termo) e na Cruzadinha (a dica é a pista).
//     Termo: uma palavra, 4 a 12 letras. A dica não pode entregar o termo.
//   AFIRMACOES: "certo ou errado" (estilo Cebraspe) do Radar do Tico. A
//     explicação começa pelo gabarito ("Certo." / "Errado.").
// Como as questões, este conteúdo passa pela revisão de um professor antes
// de crescer (docs/STATUS.md).

import type { DisciplinaId } from './types.js';

export interface Termo {
  disciplina: DisciplinaId;
  termo: string; // como se escreve, com acento
  dica: string;
}

export interface Afirmacao {
  id: string;
  disciplina: DisciplinaId;
  texto: string;
  certo: boolean;
  explicacao: string;
}

// Só as letras, sem acento nem cedilha, em maiúsculas (é o que vai na grade).
export function letras(s: string): string {
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '').toUpperCase().replace(/[^A-Z]/g, '');
}

const termos = (disciplina: DisciplinaId, lista: [string, string][]): Termo[] =>
  lista.map(([termo, dica]) => ({ disciplina, termo, dica }));

export const GLOSSARIO: Termo[] = [
  ...termos('portugues', [
    ['CRASE', 'Fusão da preposição a com o artigo a, marcada pelo acento grave.'],
    ['PRÓCLISE', "Pronome oblíquo antes do verbo: 'Não me diga'."],
    ['ÊNCLISE', "Pronome oblíquo depois do verbo: 'Diga-me'."],
    ['MESÓCLISE', "Pronome no meio do verbo, no futuro: 'dir-te-ei'."],
    ['SUJEITO', 'Termo da oração sobre o qual se declara algo.'],
    ['PREDICADO', 'Tudo o que se declara sobre o sujeito na oração.'],
    ['VOCATIVO', "Termo usado para chamar alguém: 'Maria, venha cá'."],
    ['APOSTO', 'Termo que explica outro, geralmente entre vírgulas.'],
    ['SINÔNIMO', 'Palavra de sentido igual ou parecido ao de outra.'],
    ['ANTÔNIMO', 'Palavra de sentido contrário ao de outra: alto e baixo.'],
    ['PARÔNIMO', 'Palavras parecidas na escrita, de sentidos diferentes: descrição e discrição.'],
    ['HOMÔNIMO', 'Mesma pronúncia, sentidos diferentes: sessão e cessão.'],
    ['OXÍTONA', 'Palavra com a sílaba tônica na última sílaba: café, jacaré.'],
    ['PAROXÍTONA', 'Palavra com a sílaba tônica na penúltima sílaba: caráter, lápis.'],
    ['CONJUNÇÃO', 'Palavra que liga orações ou termos: mas, porque, embora.'],
    ['PLEONASMO', 'Repetição de ideia; vira vício quando é inútil: subir para cima.'],
    ['METÁFORA', "Comparação sem o 'como': 'Ele é uma fera'."],
  ]),
  ...termos('rlm', [
    ['TAUTOLOGIA', 'Proposição composta que é sempre verdadeira, em qualquer caso.'],
    ['CONTRADIÇÃO', 'Proposição composta que é sempre falsa, em qualquer caso.'],
    ['CONTINGÊNCIA', 'Proposição que pode ser verdadeira ou falsa, conforme os valores.'],
    ['SILOGISMO', 'Argumento com duas premissas e uma conclusão.'],
    ['PREMISSA', 'Afirmação aceita como ponto de partida de um argumento.'],
    ['CONJUNÇÃO', "Conectivo 'e': só é verdadeiro se as duas partes forem."],
    ['DISJUNÇÃO', "Conectivo 'ou': só é falso se as duas partes forem falsas."],
    ['CONDICIONAL', "Conectivo 'se... então': falso só com V na 1ª e F na 2ª."],
    ['NEGAÇÃO', 'Operação que troca o valor lógico: o verdadeiro vira falso.'],
    ['PROPOSIÇÃO', 'Frase declarativa que pode ser julgada verdadeira ou falsa.'],
    ['PERMUTAÇÃO', 'Modos de ordenar todos os elementos: n fatorial.'],
    ['ARRANJO', 'Agrupamento em que a ordem dos elementos importa.'],
    ['COMBINAÇÃO', 'Agrupamento em que a ordem dos elementos não importa.'],
    ['FATORIAL', 'Produto dos inteiros de 1 até n: 4! = 24.'],
    ['PORCENTAGEM', 'Razão com denominador 100: 25 em cada 100.'],
    ['PROPORÇÃO', 'Igualdade entre duas razões: 2 está para 4 assim como 3 para 6.'],
  ]),
  ...termos('informatica', [
    ['NAVEGADOR', 'Programa que abre páginas da internet: Chrome, Firefox, Edge.'],
    ['FIREWALL', 'Barreira que filtra o tráfego de rede e bloqueia conexões.'],
    ['PHISHING', 'Golpe com mensagem falsa que tenta roubar senhas e dados.'],
    ['MALWARE', 'Nome geral de programa malicioso: vírus, worm, cavalo de troia.'],
    ['BACKUP', 'Cópia de segurança dos dados, para recuperar em caso de perda.'],
    ['PLANILHA', 'Documento de linhas, colunas e fórmulas, como no Excel e no Calc.'],
    ['PROTOCOLO', 'Regras de comunicação entre computadores: HTTP, TCP/IP.'],
    ['HARDWARE', 'Parte física do computador: placa-mãe, memória, teclado.'],
    ['SOFTWARE', 'Parte lógica: programas e sistemas que rodam no computador.'],
    ['CRIPTOGRAFIA', 'Técnica que embaralha dados para só quem tem a chave ler.'],
    ['RANSOMWARE', 'Praga que cifra os arquivos e pede resgate para liberar.'],
    ['SPAM', 'Mensagem em massa não solicitada, geralmente propaganda.'],
    ['INTRANET', 'Rede interna de uma organização, com as tecnologias da internet.'],
    ['NUVEM', 'Serviços e arquivos em servidores acessados pela internet.'],
    ['COOKIE', 'Pequeno arquivo que o site grava no navegador para lembrar preferências.'],
    ['ATALHO', 'Combinação de teclas que executa um comando: Ctrl+C copia.'],
    ['WORM', 'Praga que se espalha sozinha pela rede, sem arquivo hospedeiro.'],
  ]),
  ...termos('constitucional', [
    ['SOBERANIA', 'Fundamento da República: o Estado não se submete a poder externo.'],
    ['CIDADANIA', 'Fundamento da República ligado à participação do povo na política.'],
    ['DIGNIDADE', 'Fundamento da República que põe a pessoa humana no centro do Estado.'],
    ['PLURALISMO', 'Fundamento da República: convivência de ideias e partidos diferentes.'],
    ['PÉTREA', 'Tipo de cláusula que emenda nenhuma pode abolir.'],
    ['PLEBISCITO', 'Consulta ao povo feita ANTES de o ato ser editado.'],
    ['REFERENDO', 'Consulta ao povo feita DEPOIS do ato, para confirmar ou rejeitar.'],
    ['INICIATIVA', 'Projeto de lei do povo: 1% do eleitorado nacional, em 5 estados.'],
    ['FEDERAÇÃO', 'Forma de Estado do Brasil: união indissolúvel de entes autônomos.'],
    ['REPÚBLICA', 'Forma de governo do Brasil, com mandatos temporários e eletivos.'],
    ['ASILO', 'Proteção concedida a estrangeiro perseguido por motivo político.'],
    ['SUFRÁGIO', 'Direito de votar e ser votado; no Brasil, universal.'],
    ['EMENDA', 'Mudança na Constituição: dois turnos, três quintos em cada Casa.'],
    ['IMUNIDADE', 'Proteção do parlamentar por opiniões, palavras e votos.'],
    ['VETO', 'Discordância do Presidente com um projeto aprovado pelo Congresso.'],
    ['SANÇÃO', 'Concordância do Presidente com o projeto de lei aprovado.'],
  ]),
  ...termos('administrativo', [
    ['LEGALIDADE', 'O administrador só pode fazer o que a lei permite.'],
    ['MORALIDADE', 'Princípio que exige ética, honestidade e boa-fé na Administração.'],
    ['PUBLICIDADE', 'Princípio da transparência e da divulgação oficial dos atos.'],
    ['EFICIÊNCIA', 'Princípio incluído pela EC 19/1998: resultado com qualidade e economia.'],
    ['AUTOTUTELA', 'Poder de anular os próprios atos ilegais e revogar os inconvenientes.'],
    ['REVOGAÇÃO', 'Retirada de ato válido por conveniência e oportunidade.'],
    ['ANULAÇÃO', 'Retirada de ato ilegal, pela Administração ou pelo Judiciário.'],
    ['AUTARQUIA', 'Pessoa jurídica de direito público criada por lei: o INSS, por exemplo.'],
    ['CONCESSÃO', 'Delegação de serviço público por contrato, após licitação.'],
    ['LICITAÇÃO', 'Procedimento para escolher a proposta mais vantajosa antes de contratar.'],
    ['PREGÃO', 'Modalidade de licitação para bens e serviços comuns.'],
    ['MÉRITO', 'Juízo de conveniência e oportunidade no ato discricionário.'],
    ['PRESUNÇÃO', 'Atributo: o ato vale como legítimo e verdadeiro até prova em contrário.'],
    ['HIERARQUIA', 'Poder de ordenar, coordenar e rever a atuação dos subordinados.'],
    ['IMPROBIDADE', 'Ato desonesto do agente público, punido pela Lei 8.429/1992.'],
    ['POLÍCIA', 'Poder de limitar direitos individuais em favor do interesse público.'],
    ['CONVALIDAÇÃO', 'Correção de ato com vício sanável, com efeitos desde a origem.'],
  ]),
];

const afirmacoes = (disciplina: DisciplinaId, prefixo: string, lista: [string, boolean, string][]): Afirmacao[] =>
  lista.map(([texto, certo, explicacao], i) => ({ id: `${prefixo}-${i + 1}`, disciplina, texto, certo, explicacao }));

export const AFIRMACOES: Afirmacao[] = [
  ...afirmacoes('portugues', 'radar-pt', [
    ["Em 'Vou à escola', o acento grave indica a fusão da preposição a com o artigo a.", true,
      "Certo. Quem vai, vai a algum lugar (preposição), e 'escola' aceita o artigo a: a + a = à."],
    ["Usa-se crase antes de verbo, como em 'Começou à estudar'.", false,
      "Errado. Verbo não aceita artigo; sem artigo, não há crase: 'começou a estudar'."],
    ["Em 'Não me disseram nada', a palavra 'não' atrai o pronome para antes do verbo.", true,
      'Certo. Palavras negativas são fator de próclise.'],
    ["Pela norma-padrão, é correto começar a frase com pronome átono: 'Me empresta o livro'.", false,
      "Errado. A norma-padrão não admite começar frase com pronome átono: 'Empresta-me o livro'."],
    ["'Fazem dois anos que não o vejo' está errado; o certo é 'Faz dois anos'.", true,
      'Certo. O verbo fazer indicando tempo decorrido é impessoal e fica no singular.'],
    ["'Haviam muitas pessoas na fila' está correto pela norma-padrão.", false,
      "Errado. Haver no sentido de existir é impessoal: 'Havia muitas pessoas'."],
    ["O vocativo é separado por vírgula: 'Maria, feche a porta'.", true,
      'Certo. O vocativo é sempre isolado por vírgula.'],
    ["Pode-se separar sujeito e verbo com vírgula: 'Os alunos, estudaram muito'.", false,
      'Errado. Não se separa o sujeito do verbo por vírgula.'],
    ["'Café', 'jacaré' e 'você' levam acento por serem oxítonas terminadas em e.", true,
      'Certo. Oxítonas terminadas em a, e, o (seguidas ou não de s), em e ens são acentuadas.'],
    ["Depois do Acordo Ortográfico, 'ideia' e 'assembleia' continuam com acento agudo.", false,
      'Errado. O Acordo tirou o acento dos ditongos abertos ei e oi das paroxítonas: ideia, assembleia, heroico.'],
    ["Toda proparoxítona é acentuada, como 'lâmpada' e 'público'.", true,
      'Certo. A regra não tem exceção: toda proparoxítona leva acento.'],
    ["'Mas' e 'mais' têm o mesmo sentido e podem ser trocados sem mudar a frase.", false,
      "Errado. 'Mas' indica oposição (porém); 'mais' indica quantidade ou intensidade."],
    ["Em 'Assisti ao filme', o verbo assistir, no sentido de ver, pede a preposição a.", true,
      'Certo. Assistir no sentido de ver é transitivo indireto: assistir a algo.'],
    ["Pela norma-padrão, 'Prefiro café do que chá' está correto.", false,
      "Errado. Preferir pede a preposição a: 'Prefiro café a chá'."],
    ["'Porque', junto e sem acento, introduz explicação ou causa: 'Faltei porque estava doente'.", true,
      "Certo. É conjunção explicativa ou causal."],
    ["No fim da pergunta, escreve-se 'por que' separado e sem acento: 'Você faltou por que?'.", false,
      "Errado. No fim da frase, usa-se 'por quê', com acento."],
  ]),
  ...afirmacoes('rlm', 'radar-rl', [
    ["A negação de 'Todo aluno estudou' é 'Algum aluno não estudou'.", true,
      "Certo. Para negar 'todo', basta um caso contrário."],
    ["A negação de 'Todo aluno estudou' é 'Nenhum aluno estudou'.", false,
      "Errado. 'Nenhum' é o extremo oposto; a negação é 'Algum aluno não estudou'."],
    ["A proposição 'p ou não p' é uma tautologia.", true,
      'Certo. Em qualquer caso, uma das partes é verdadeira, então a disjunção é sempre verdadeira.'],
    ["'p e q' é verdadeira quando só uma das proposições é verdadeira.", false,
      'Errado. A conjunção só é verdadeira quando as duas partes são verdadeiras.'],
    ["'Se chove, então a rua molha' só é falsa se chover e a rua não molhar.", true,
      'Certo. A condicional só é falsa quando a primeira parte é verdadeira e a segunda, falsa.'],
    ["'Se p, então q' é equivalente a 'Se q, então p'.", false,
      "Errado. Essa é a recíproca, que não é equivalente. A equivalente é 'Se não q, então não p'."],
    ["A negação de 'p e q' é 'não p ou não q'.", true,
      'Certo. É uma das leis de De Morgan.'],
    ["A negação de 'p ou q' é 'não p ou não q'.", false,
      "Errado. Pela lei de De Morgan, a negação é 'não p e não q'."],
    ['Uma tabela-verdade com 3 proposições simples tem 8 linhas.', true,
      'Certo. São 2³ = 8 combinações de V e F.'],
    ['Há 12 maneiras de ordenar 4 livros diferentes em uma prateleira.', false,
      'Errado. É uma permutação de 4 elementos: 4! = 24 maneiras.'],
    ['Com 5 pessoas, é possível formar 10 duplas diferentes.', true,
      'Certo. A ordem não importa: (5 × 4) ÷ 2 = 10.'],
    ['Um aumento de 10% seguido de um desconto de 10% faz o preço voltar ao valor inicial.', false,
      'Errado. 100 vira 110 e depois 99: no fim, o preço cai 1%.'],
    ['Em uma turma de 150 alunos, 20% correspondem a 30 alunos.', true,
      'Certo. 150 × 0,2 = 30, ou seja, 20 em cada 100.'],
    ['Se 3 operários fazem um muro em 6 dias, 6 operários fazem o mesmo muro em 12 dias.', false,
      'Errado. As grandezas são inversamente proporcionais: com o dobro de operários, o tempo cai pela metade, 3 dias.'],
    ["'Feche a porta!' não é proposição, porque não pode ser julgada verdadeira ou falsa.", true,
      'Certo. Ordens, perguntas e exclamações não são proposições.'],
    ['Ao lançar um dado comum, a chance de sair número par é de 1 em 3.', false,
      'Errado. São 3 pares (2, 4 e 6) em 6 resultados: 3/6 = 1/2.'],
  ]),
  ...afirmacoes('informatica', 'radar-inf', [
    ['O backup deve ficar, de preferência, em local diferente do equipamento original.', true,
      'Certo. Assim ele sobrevive a roubo, incêndio ou defeito do equipamento.'],
    ['O firewall, sozinho, remove vírus que já estão instalados no computador.', false,
      'Errado. O firewall filtra o tráfego de rede; quem remove vírus é o antivírus.'],
    ['Phishing é um golpe que usa mensagens falsas para roubar dados, como senhas e cartões.', true,
      'Certo. O golpista se passa por banco, loja ou órgão público.'],
    ['O protocolo HTTPS transmite os dados sem nenhuma criptografia.', false,
      'Errado. O S indica conexão segura, com criptografia (TLS).'],
    ['No Excel, =SOMA(A1:A3) soma os valores de A1, A2 e A3.', true,
      'Certo. Os dois-pontos indicam o intervalo de A1 até A3.'],
    ['No Excel, =MÉDIA(A1;A3) calcula a média de A1 até A3.', false,
      'Errado. O ponto e vírgula separa argumentos: só entram A1 e A3. Para o intervalo, use A1:A3.'],
    ['A memória RAM é volátil: perde o conteúdo quando o computador é desligado.', true,
      'Certo. Por isso é preciso salvar o trabalho no disco.'],
    ['Ransomware é um programa que protege os arquivos do usuário contra ataques.', false,
      'Errado. Ransomware é uma praga que cifra os arquivos e exige resgate para liberá-los.'],
    ['A intranet é uma rede privada que usa as mesmas tecnologias da internet.', true,
      'Certo. Usa protocolos como TCP/IP e HTTP, mas fica restrita à organização.'],
    ['O worm precisa que o usuário abra um arquivo hospedeiro para se espalhar.', false,
      'Errado. O worm se propaga sozinho pela rede; é o vírus que depende de um hospedeiro.'],
    ['No e-mail, quem está em Cco recebe a mensagem sem que os outros vejam seu endereço.', true,
      'Certo. Cco é a cópia oculta: esses endereços ficam escondidos dos demais.'],
    ['A navegação anônima esconde do provedor de internet todos os sites visitados.', false,
      'Errado. Ela só deixa de guardar histórico e cookies no próprio aparelho; o provedor e os sites ainda veem o acesso.'],
    ['O atalho Ctrl+Z desfaz a última ação na maioria dos programas.', true,
      'Certo. Ctrl+Y costuma refazer.'],
    ['Hardware é o nome dado aos programas instalados no computador.', false,
      'Errado. Hardware é a parte física; programas são software.'],
    ['A verificação em duas etapas combina, por exemplo, a senha com um código enviado ao celular.', true,
      'Certo. Mesmo que a senha vaze, o invasor ainda precisa do segundo fator.'],
    ['Cookies são vírus que o site grava no computador do usuário.', false,
      'Errado. Cookies são pequenos arquivos de texto com dados da navegação, como preferências; não são vírus.'],
  ]),
  ...afirmacoes('constitucional', 'radar-const', [
    ['A soberania, a cidadania e a dignidade da pessoa humana são fundamentos da República.', true,
      'Certo. Estão no art. 1º, ao lado dos valores sociais do trabalho e da livre iniciativa e do pluralismo político.'],
    ['Construir uma sociedade livre, justa e solidária é um fundamento da República.', false,
      'Errado. É um objetivo fundamental (art. 3º), não um fundamento (art. 1º).'],
    ['A casa é asilo inviolável, mas pode-se entrar nela sem consentimento em caso de flagrante delito.', true,
      'Certo. Art. 5º, XI: também em desastre, para prestar socorro, ou de dia, por ordem judicial.'],
    ['Com ordem judicial, a polícia pode entrar numa casa a qualquer hora da noite.', false,
      'Errado. Por ordem judicial, só durante o dia (art. 5º, XI).'],
    ['O habeas corpus protege a liberdade de locomoção.', true,
      'Certo. Art. 5º, LXVIII: cabe contra violência ou coação ilegal na liberdade de ir e vir.'],
    ['O habeas data é o remédio constitucional que protege a liberdade de locomoção.', false,
      'Errado. O habeas data serve para conhecer ou corrigir dados sobre a pessoa em registros públicos; locomoção é habeas corpus.'],
    ['Os direitos e garantias individuais não podem ser abolidos por emenda constitucional.', true,
      'Certo. São cláusula pétrea (art. 60, § 4º, IV).'],
    ['Uma emenda constitucional é aprovada em turno único, por maioria simples.', false,
      'Errado. Exige dois turnos em cada Casa do Congresso e três quintos dos votos (art. 60, § 2º).'],
    ['O voto é obrigatório para maiores de 18 anos e facultativo para maiores de 70.', true,
      'Certo. Art. 14, § 1º; também é facultativo para analfabetos e para quem tem 16 ou 17 anos.'],
    ['No Brasil, o voto é facultativo para todos os cidadãos.', false,
      'Errado. É obrigatório para maiores de 18 anos, com exceções: analfabetos, maiores de 70 e jovens de 16 e 17.'],
    ['O plebiscito é convocado antes da edição do ato; o referendo, depois.', true,
      'Certo. No referendo, o povo confirma ou rejeita um ato já editado.'],
    ['Como todos são iguais perante a lei, a Constituição proíbe qualquer tratamento diferente entre pessoas.', false,
      'Errado. A igualdade material permite tratar de forma diferente quem está em situação diferente, como nas ações afirmativas.'],
    ['A Constituição garante a livre manifestação do pensamento, mas proíbe o anonimato.', true,
      'Certo. Art. 5º, IV: é livre a manifestação do pensamento, sendo vedado o anonimato.'],
    ['A prática do racismo é crime afiançável e prescreve em cinco anos.', false,
      'Errado. É crime inafiançável e imprescritível, sujeito a reclusão (art. 5º, XLII).'],
    ['A República é formada pela união indissolúvel dos Estados, dos Municípios e do Distrito Federal.', true,
      'Certo. Art. 1º, caput: é assim que se forma a República Federativa do Brasil.'],
    ['Um Estado pode se separar da Federação por plebiscito da sua população.', false,
      'Errado. A união é indissolúvel, e a forma federativa é cláusula pétrea (art. 60, § 4º, I).'],
  ]),
  ...afirmacoes('administrativo', 'radar-adm', [
    ['Legalidade, impessoalidade, moralidade, publicidade e eficiência são princípios expressos no art. 37 da Constituição.', true,
      'Certo. São os princípios do LIMPE.'],
    ['O princípio da eficiência está no texto original da Constituição de 1988.', false,
      'Errado. Foi incluído pela Emenda Constitucional 19, de 1998.'],
    ['Pelo princípio da legalidade, o administrador público só pode fazer o que a lei permite.', true,
      'Certo. Já o particular pode fazer tudo o que a lei não proíbe.'],
    ['A Administração só pode anular seus atos ilegais com autorização do Poder Judiciário.', false,
      'Errado. Pela autotutela, ela mesma anula seus atos ilegais (Súmula 473 do STF).'],
    ['A revogação retira um ato válido por conveniência e oportunidade.', true,
      'Certo. Quem revoga é a própria Administração, e os efeitos já produzidos são mantidos.'],
    ['O Poder Judiciário pode revogar atos do Poder Executivo por considerá-los inconvenientes.', false,
      'Errado. O Judiciário controla a legalidade e anula atos ilegais; revogar por conveniência cabe a quem editou o ato.'],
    ['Presunção de legitimidade, imperatividade e autoexecutoriedade são atributos do ato administrativo.', true,
      'Certo. A doutrina também aponta a tipicidade.'],
    ['Todos os atos administrativos têm o atributo da autoexecutoriedade.', false,
      'Errado. Nem todos: a cobrança de multa, por exemplo, depende de execução na Justiça.'],
    ['A autarquia é pessoa jurídica de direito público, criada por lei específica.', true,
      'Certo. Art. 37, XIX, da Constituição.'],
    ['Empresa pública e sociedade de economia mista são pessoas jurídicas de direito público.', false,
      'Errado. São pessoas jurídicas de direito privado da Administração Indireta.'],
    ['O poder de polícia permite limitar direitos individuais em favor do interesse público.', true,
      'Certo. Exemplos: fiscalização sanitária e interdição de estabelecimento irregular.'],
    ['O poder disciplinar permite punir qualquer particular, mesmo sem vínculo com a Administração.', false,
      'Errado. O poder disciplinar alcança servidores e quem tem vínculo especial com a Administração; para os demais, é poder de polícia.'],
    ['O pregão é a modalidade de licitação para bens e serviços comuns.', true,
      'Certo. Na Lei 14.133/2021, ele é adotado sempre que o objeto for bem ou serviço comum.'],
    ['A Lei 14.133/2021 manteve a tomada de preços e o convite como modalidades de licitação.', false,
      'Errado. A nova lei acabou com essas modalidades e criou o diálogo competitivo.'],
    ['Depois da Lei 14.230/2021, só há improbidade administrativa com dolo.', true,
      'Certo. A modalidade culposa deixou de existir.'],
    ['A publicidade oficial pode usar nomes e imagens que promovam o administrador.', false,
      'Errado. A Constituição proíbe a promoção pessoal na publicidade oficial (art. 37, § 1º).'],
  ]),
];
